#!/usr/bin/perl

# -----------------------------------------------------------------------------
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# -----------------------------------------------------------------------------

# - modules >
use warnings;
use strict;
use Term::ANSIColor;
use PortageXS v0.3.0;
use Path::Tiny qw( path );
use Digest::SHA1 qw( sha1_hex );

# - init vars & constants >
my $VERSION			= '0.17';

use Gentoo::App::PerlInfo;
my $instance = Gentoo::App::PerlInfo->new_with_args();
$instance->run;

my $pxs = $instance->_pxs;
foreach my $this_category ($pxs->getPortageXScategorylist('perl')) {
	my $category_str_length = length($this_category)+1;
	my $seen = 0;
	$instance->_print_section_label("Installed packages from category ".$this_category);
	foreach($pxs->searchInstalledPackage($this_category."/*")) {
		$seen++;
		print "   ".substr($_,$category_str_length,length($_)-$category_str_length). " " . $instance->use_for($_) . "\n";
	}
	print "   none\n" unless $seen;
	print "\n";
}

foreach my $this_category ('virtual') {
	my $category_str_length = length($this_category)+1;
	$instance->_print_section_label("Installed virtuals with perl- prefix");
	my $seen = 0;
	foreach($pxs->searchInstalledPackage($this_category."/*")) {
		next unless $_ =~ /virtual\/perl-/;
		$seen++;
		print "   ".substr($_,$category_str_length,length($_)-$category_str_length)." " . $instance->use_for($_) . "\n";
	}
	print "   none\n" unless $seen;
	print "\n";
}

$instance->_print_section_label("eclasses");
foreach my $eclassName ("perl-app","perl-functions","perl-module") {
	printf "   %15s: %s\n", $eclassName, $instance->eclass_desc( $eclassName );
}
print "\n";
exit(0);

# - Here comes the POD >

=head1 NAME

perl-info - gather systems perl info

=head1 SYNOPSIS

perl-info

=head1 DESCRIPTION

perl-info shall help developers getting sufficient information about the
users perl installation when needed.

=head1 ARGUMENTS

perl-info does not have any arguments yet.

=head1 AUTHOR

Christian Hartmann <ian@gentoo.org>

=head1 LICENSE

Copyright (C) 2006, 2007  Christian Hartmann

This program is free software; you can redistribute it and/or modify
it under the terms of The GNU General Public License, Version 2,
or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

=cut
